sudo: required

language: node_js
node_js:
  - "4.1"

services:
  - docker
  - cassandra

env:
  - DOCKER_HOST_IP=localhost
  - CASSANDRA_IP=127.0.0.1

before_install:
  - docker pull t3g7/api
  - docker run -d -p 8080:8080 t3g7/api $CASSANDRA_IP
  - docker ps -a
  - usr/local/cassandra/bin/cqlsh -f test/init.cql

script:
  - npm test
