sudo: required

language: node_js
node_js:
  - "4.1"

services:
  - cassandra

env:
  - DOCKER_HOST_IP=localhost
  - CASSANDRA_IP=127.0.0.1

before_install:
  - cqlsh -f test/init.cql

script:
  - npm test
